### PR TITLE
fix - tag missing for aws_kinesis_firehose_delivery_stream resource

### PR DESCRIPTION
**Pull request by K-Nakul-K**
# Description

LogDeliveryEnabled = true, Tag was missing for aws_kinesis_firehose_delivery_stream resource

Fixes  https://github.com/coralogix/terraform-coralogix-aws/issues/194

# How Has This Been Tested?

Tested on my env. by running terraform apply multiple times.

# Checklist:
- [ ] I have updated the relevant example in the examples directory for the module.
- [ ] I have updated the relevant test file for the module.
- [ ] This change does not affect module (e.g. it's readme file change)

### CODE REVIEW

**Comment by cazorla19** [comment]
please update the `CHANGELOG.md` with this change as a bug fix, otherwise the change itself lgtm

**Comment by K-Nakul-K** [comment]
> please update the `CHANGELOG.md` with this change as a bug fix, otherwise the change itself lgtm

Done.

**Comment by ryantanjunming** [comment]
Hi @K-Nakul-K , can i have some documentation on this `LogDeliveryEnabled = true` being added on for `aws_kinesis_firehose_delivery_stream`?

I only see https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/AWS-logs-and-resource-policy.html which looks more like a resource policy

**Comment by K-Nakul-K** [comment]
> Hi @K-Nakul-K , can i have some documentation on this `LogDeliveryEnabled = true` being added on for `aws_kinesis_firehose_delivery_stream`?
> 
> I only see https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/AWS-logs-and-resource-policy.html which looks more like a resource policy

https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/AWS-logs-and-resource-policy.html

The Firehose stream must have the tag LogDeliveryEnabled set to true.

image

**Comment by ryantanjunming** [comment]
@K-Nakul-K Is this change policy also required for firehose_iam role? 

`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "firehose:PutRecord",
                "firehose:PutRecordBatch",
                "firehose:ListTagsForDeliveryStream"
            ],
            "Resource": "*",
            "Condition": {
                "StringEquals": {
                    "aws:ResourceTag/LogDeliveryEnabled": "true"
                }
            },
            "Effect": "Allow"
        }
    ]
}`

**Comment by ryantanjunming** [comment]
@K-Nakul-K pls sign the Contributor License Agreement

**Comment by K-Nakul-K** [comment]
> @K-Nakul-K Is this change policy also required for firehose_iam role?
> 
> `{ "Version": "2012-10-17", "Statement": [ { "Action": [ "firehose:PutRecord", "firehose:PutRecordBatch", "firehose:ListTagsForDeliveryStream" ], "Resource": "*", "Condition": { "StringEquals": { "aws:ResourceTag/LogDeliveryEnabled": "true" } }, "Effect": "Allow" } ] }`

My use case is deliver of logs from AWS Network firewall to firehose which uses V1 permission (as per documentation)
image

and **AWSServiceRoleForLogDeliveryPolicy** role is already created by AWS. This service-linked role grants permission for all Firehose delivery streams that have the LogDeliveryEnabled tag set to true.
image

So short answer not required. :)

**Comment by K-Nakul-K** [comment]
> @K-Nakul-K pls sign the Contributor License Agreement

K-Nakul-K is my public id, from which I signed in. Where are username that you see if my org. laptop, not sure if I could really sign from that contributor name. If there any workaround for this?

**Comment by ryantanjunming** [comment]
@K-Nakul-K I copied over your PR since the contributor license cant be signed by the org laptop one. 
I'll see to it getting merged, thanks for the help

https://github.com/coralogix/terraform-coralogix-aws/pull/197

**Comment by K-Nakul-K** [comment]
@ryantanjunming Thank You! :)

**Pull request closed without merging**
